version: '3'
services:
  chatappui:
    build:
      context: /root/Desktop/Apps/ChatApp/ChatAppUI/
      network: host
      dockerfile: Dockerfile
    network_mode: "host"
  chatappapi:
    build:
      context: /root/Desktop/Apps/ChatApp/ChatAppBackend/
      network: host
      dockerfile: Dockerfile
    network_mode: "host"
  nginx:
    build:
     context: /root/Desktop/Apps/Server/
     network: host
     dockerfile: Dockerfile
    network_mode: "host"
    volumes:
      - /root/Desktop/Apps/Server/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - chatappui
      - chatappapi
