version: '3'
services:
  chatappui:
    build:
      context: /root/Desktop/Apps/ChatApp/ChatAppUI/
      network: host
      dockerfile: Dockerfile
    ports:
      - "4200:80"
  chatappapi:
    build:
      context: /root/Desktop/Apps/ChatApp/ChatAppBackend/
      network: host
      dockerfile: Dockerfile
    ports:
      - "3000:80"
  nginx:
    build:
      context: /root/Desktop/Apps/Server/
      network: host
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - /root/Desktop/Apps/Server/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - chatappui
      - chatappapi
